[build-system]

requires = ['setuptools']
build-backend = "setuptools.build_meta"

[project]

name = 'Load_utils'
dynamic = ['dependencies', 'authors', 'classifiers', 'license', 'readme', 'description']
version = '1.0'

[tool.setuptools.dynamic]

dependencies = { file = ['requirements.txt'] }
